# @package _global_.model
_target_: urban_seg.models.segmentation_model.SegmentationModel

backbone:
  name: resnet101
  pretrained: true
  output_stride: 16
  replace_stride_with_dilation: [false, true, true]

head:
  name: deeplab_head
  aspp_dilations: [6, 12, 18]
  low_level_channels: 48
  dropout: 0.1

num_classes: ${data.num_classes}
